# WARNING:
#
#===================DO NOT MODIFY================================
#
# THIS FILE IS AUTO GENERATED AND IS ALWAYS OVERWRITTEN by PFPGEN
# DO NOT ADD USER CODE IN THIS FILE.
# THIS FILE IS INCLUDED by the CMakeLists.txt of:
#       src/BEHAVIOURAL
#
set(BEHAVIOURALGENSRCS
${CMAKE_CURRENT_SOURCE_DIR}/qr.h
${CMAKE_CURRENT_SOURCE_DIR}/qw.h
${CMAKE_CURRENT_SOURCE_DIR}/queue.h
${CMAKE_CURRENT_SOURCE_DIR}/top.h
${CMAKE_CURRENT_SOURCE_DIR}/top.cpp
${CMAKE_CURRENT_SOURCE_DIR}/writer.h
${CMAKE_CURRENT_SOURCE_DIR}/writer.cpp
${CMAKE_CURRENT_SOURCE_DIR}/reader.h
${CMAKE_CURRENT_SOURCE_DIR}/reader.cpp
)
